### ISSUE TITLE
境外输入，遗漏了浙江的8例

### ISSUE THREAD

**Issue by haoyuns** [839Studio/Novel-Coronavirus-Updates#101]
在文档里筛选「境外输入」条目，好像遗漏了 3.1-3.2 意大利输入浙江的 8 例，数据来源于浙江卫健委：
- http://www.zjwjw.gov.cn/art/2020/3/2/art_1202194_42047620.html
- http://www.zjwjw.gov.cn/art/2020/3/3/art_1202194_42060354.html

**Comment by 839Studio** [comment]
浙江最开始没有单列出境外输入，所以这两条当时应该是放在丽水市里了。今天会但列出来。谢谢！
