### ISSUE TITLE
能否增加实际发生时间?

### ISSUE THREAD

**Issue by wuyu84** [839Studio/Novel-Coronavirus-Updates#102]
根据报道时间计算的频数跟官网发布的总有对不上的。不知道您能否增加实际发生时间这个变量。
比如官方16日发布的新闻里面写的是”截止到15日24点……“这个16日是您的”报道时间“变量，能否增加这个”15日“实际发生日期变量？ 谢谢

**Comment by 839Studio** [comment]
很抱歉，我们现在可能没有人手来做这个修订。其次，我们之所以选择报道时间，而非发生时间，是因为，有一些情况下，发生时间无法确定，个别省的通报周期是前一天的8点到后一天的8点（举个例子），我们无法确认到底有多少是前一天发生的，有多少是后一天发生的。

**Comment by wuyu84** [comment]
明白了,感谢您团队的付出.
