### ISSUE TITLE
文件 Updates_NC.csv 编码错误

### ISSUE THREAD

**Issue by sutra** [839Studio/Novel-Coronavirus-Updates#176]
最近几天出现了3天的更新都是文件编码错误：

https://github.com/839Studio/Novel-Coronavirus-Updates/pull/167
https://github.com/839Studio/Novel-Coronavirus-Updates/pull/170
https://github.com/839Studio/Novel-Coronavirus-Updates/pull/175

**Comment by 839Studio** [comment]
已改变成utf-8的编码
