### ISSUE TITLE
数据的日期

### ISSUE THREAD

**Issue by sutra** [839Studio/Novel-Coronavirus-Updates#39]
cat Updates_NC.csv | iconv -f gbk -t utf-8 | grep '上海' | awk -F',' '$2 == "上海" {sum[$1] += $4} END {for( i in sum) { print i "\t" sum[i] }}' | sort
1月26日	7
1月27日	13
1月28日	13
1月29日	30
1月30日	16
1月31日	23
2月10日	7 // 2月10日0—24时，上海新增确诊病例7例 http://wsjkw.sh.gov.cn/xwfb/20200211/023cc24ccf6c46019ba5b25de4886fc7.html
2月11日	4 // 2月11日0—24时，上海新增确诊病例4例 http://wsjkw.sh.gov.cn/xwfb/20200212/18294c1cae944e1989a3c7f35ef3413c.html
2月12日	8 // 2月12日0—24时，上海新增确诊病例7例 http://wsjkw.sh.gov.cn/xwfb/20200213/34748b8d88c545a6a2399209676d76cd.html
2月13日	4 // 2月13日0—24时，上海新增确诊病例5 http://wsjkw.sh.gov.cn/xwfb/20200214/21b4325ffde8430586296c3094889fd4.html
2月1日	34
2月2日	13
2月3日	21
2月4日	16
2月5日	24
2月6日	14
2月7日	20 // 2月7日0—24时，上海新增确诊病例12例 http://wsjkw.sh.gov.cn/xwfb/20200208/f3882592b1144b558a13a5a9c4ac4a9f.html
2月8日	9 // 2月8日0—24时，上海新增确诊病例11例 http://wsjkw.sh.gov.cn/xwfb/20200209/033cf9bb5c694a41929a093f6c386482.html
2月9日	6 // 2月9日0—24时，上海新增确诊病例3例 http://wsjkw.sh.gov.cn/xwfb/20200210/6874c20ccc0d4e7bb205ee61a8d5fbe7.html

所以“报道日期”并不能算作卫健委公布的新增日期？

**Comment by 839Studio** [comment]
报道日期和通报日期可能会有最多一天的差别。
