### ISSUE TITLE
建议从海外移除中国

### ISSUE THREAD

**Issue by TonySue2000** [839Studio/Novel-Coronavirus-Updates#73]
![image](https://user-images.githubusercontent.com/44887097/75732805-820d2600-5d2e-11ea-9b57-ec67c1744d0d.png)
都说了是海外,当然不包括中国吧

**Comment by HVoltBb** [comment]
还是把“海外”改成“国家/地区”更合适

**Comment by TonySue2000** [comment]
改成"国家/地区"不如改成"全球"
把除中国以外的世界疫情汇集在一起才有可比性吧
所以我还是prefer 移除中国

**Comment by 839Studio** [comment]
已改成国际
